/**
 * Emit `dist/signal-registry-keyset.json` — the cross-language keyset that
 * Report-Engine (Python) vendors with a CI freshness diff (SPEC §5 Candidate C
 * / Q17). Runs as a tsup `onSuccess` step, after `dist/index.js` is built.
 *
 * Deterministic by construction (sorted arrays, no timestamp) because `dist/`
 * is committed to git — a non-deterministic field would churn the diff on
 * every build.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const { EXACT_REGISTRY, FAMILY_REGISTRY } = await import(
  join(root, "dist", "index.js")
);
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const exactKeys = Object.entries(EXACT_REGISTRY)
  .filter(([, entry]) => entry.lifecycle === "active")
  .map(([key]) => key)
  .sort();

const familyPrefixes = FAMILY_REGISTRY.filter(
  (family) => family.lifecycle === "active",
)
  .map((family) => family.prefix)
  .sort();

const keyset = {
  $comment:
    "GENERATED by scripts/emit-keyset.mjs at build (tsup onSuccess) — do not edit by hand. Cross-language keyset for Report-Engine (SPEC §5 Candidate C). exactKeys = full-match; familyPrefixes = startsWith-match.",
  package: pkg.name,
  version: pkg.version,
  exactKeys,
  familyPrefixes,
};

const outPath = join(root, "dist", "signal-registry-keyset.json");
writeFileSync(outPath, `${JSON.stringify(keyset, null, 2)}\n`, "utf8");

console.log(
  `[emit-keyset] wrote ${outPath} — ${exactKeys.length} active exact keys + ${familyPrefixes.length} family prefixes (v${pkg.version})`,
);
